# Generated by Django 6.0 on 2026-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('emil', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
            ],
        ),
    ]
